### ISSUE TITLE
PCAP paser error

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#108]
_From [rrpo...@gmail.com](https://code.google.com/u/104946461523556920002/) on November 03, 2011 13:12:57_

What steps will reproduce the problem? 1. running pcap parser 2. #!/usr/bin/env python2

import dpkt	# Framework for parsing packets, use python 2.6
import sys

try:
	file = open(sys.argv[1], 'rb')
	\#print sys.argv[1]
	pcap = dpkt.pcap.Reader(file)
	\#print pcap
	lines = 0
	for ts, buf in pcap:
		\#print pkts, len(buf)
		eth = dpkt.ethernet.Ethernet(buf)
		ip = eth.data
		tcp = ip.data
		lines = lines +1
	print lines
	if tcp.dport == 80 and len(tcp.data) > 0:
		http = dpkt.http.Request(tcp.data)
		print http.uri
		
	file.close()

except ValueError:
	print "Could not open file!" What is the expected output? What do you see instead? Traceback (most recent call last):
  File "pcapParser.py", line 17, in \<module>
    tcp = ip.data
AttributeError: 'str' object has no attribute 'data' What version of the product are you using? On what operating system? 1.7 Please provide any additional information below. n/a

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=81_

**Comment by kbandla** [comment]
_From [rrpo...@gmail.com](https://code.google.com/u/104946461523556920002/) on November 03, 2011 12:26:19_

Ok, figures this one out.  Now I'm just trying to print all known attributes of tcp or udp.  It keeps failing because it finds a none IP based packet.  I need a one liner that prints everything except arp.

**Comment by kbandla** [comment]
_From [timur.al...@gmail.com](https://code.google.com/u/117790548747779378711/) on March 17, 2012 16:37:19_

Not an issue with dpkt -- closing

**Status:** Invalid

**Comment by kbandla** [comment]
_From [engn...@gmail.com](https://code.google.com/u/107278081302228900545/) on July 02, 2012 07:30:22_

i have a same error. how can i fix this ? 
i m using python 2.7
my operating system  , windows7 64bit

**Comment by kbandla** [comment]
_From [engn...@gmail.com](https://code.google.com/u/107278081302228900545/) on July 02, 2012 07:32:11_

my error message is :

if tcp.dport == 80 and len(tcp.data)> 0 :
AttributeError : 'ICMP' object has no attribute 'dport'

**Comment by kbandla** [comment]
_From [agruns...@gmail.com](https://code.google.com/u/114840924801499042121/) on July 28, 2013 18:11:37_

I have a similar problem running the dpkt tutorial, but the error I get involves tcp.dport and str object not having an attribute...

    if tcp.dport == 80 and len(tcp.data) > 0:
AttributeError: 'str' object has no attribute 'dport'

**Comment by kbandla** [comment]
_From [amanroya...@gmail.com](https://code.google.com/u/115059013179953327808/) on May 02, 2014 10:50:17_

SAMPLE outputfor same issue:
62492
41325
42921
22
62493
41325
42922
22
42923
22
42924
22
Traceback (most recent call last):
  File "C:\Users\aman\parse.py", line 8, in \<mod
ule>
    tcp = ip.data
AttributeError: 'str' object has no attribute 'data'

CODE:

import dpkt
import sys
f = open('cap1.pcap','rb')
pcap = dpkt.pcap.Reader(f)
for ts, buf in pcap:
  eth = dpkt.ethernet.Ethernet(buf)
  ip = eth.data
  tcp = ip.data
  print ip.id
  print tcp.sport
