### ISSUE TITLE
import IP protocols can import modules from other packages and fail.

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#141]
_From [de...@chromium.org](https://code.google.com/u/117933008161009266207/) on October 10, 2013 14:30:25_

If you have installed a python module somewhere on your path that has the same name as a protocol listed on the ip.py module (like IP_PROTO_ROUTING attempts to import the "routing" module) your module could be imported in dpkt instead of the intended one, and latter fail because protocol.PROTOCOL is expected.

To fix this, we need to pass levels=0 to the __import__ on ip.py. Attached is the patch to fix this with an extra check.

Thanks :)

**Attachment:** [ip-import-fix.patch](http://code.google.com/p/dpkt/issues/detail?id=115)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=115_

**Comment by kbandla** [comment]
_From [de...@chromium.org](https://code.google.com/u/117933008161009266207/) on October 21, 2013 19:16:22_

Hi again!
The actual fix for this problem is passing level=1 to the __import__ .

See the patch we added in chromium: https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/HEAD/dev-python/dpkt/files/dpkt-1.8-fix-ip-import.patch

**Comment by bitonio** [comment]
Same issue happens here, even with level=1:

```
2015-06-20 00:32:22,619 [ERROR] [113:start:MainThread] 'module' object has no attribute 'AN'
Traceback (most recent call last):
[...]
    import dpkt
  File "/usr/local/lib/python2.7/dist-packages/dpkt/__init__.py", line 23, in <module>
    import ethernet
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ethernet.py", line 134, in <module>
    __load_types()
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ethernet.py", line 127, in __load_types
    mod = __import__(modname, g, level=1)
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ip6.py", line 135, in <module>
    import ip
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ip.py", line 309, in <module>
    __load_protos()
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ip.py", line 305, in __load_protos
    IP.set_proto(v, getattr(mod, name.upper()))
AttributeError: 'module' object has no attribute 'AN'
```

**Comment by kbandla** [comment]
@bitonio that might be a different problem. Do you have a `an.py` module with a `class AH` defined in it? 
Can you share the code snippet that triggered this problem?

**Comment by bitonio** [comment]
Indeed I have an an.py module, but no class AH. I'll work on a snippet (may need few days).

**Comment by bitonio** [comment]
Ok, this is an easy one:

Python 2.7.3
```
# ip show dpkt
---
Metadata-Version: 2.0
Name: dpkt
Version: 1.8.6.2
Summary: fast, simple packet creation / parsing, with definitions for the basic TCP/IP protocols
Home-page: http://dpkt.googlecode.com/
Author: Dug Song
Author-email: dugsong@monkey.org
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires:
```
```
# cat an.py
import dpkt
```
```
# python an.py
Traceback (most recent call last):
  File "an.py", line 1, in <module>
    import dpkt
  File "/usr/local/lib/python2.7/dist-packages/dpkt/__init__.py", line 23, in <module>
    import ethernet
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ethernet.py", line 134, in <module>
    __load_types()
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ethernet.py", line 127, in __load_types
    mod = __import__(modname, g, level=1)
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ip6.py", line 135, in <module>
    import ip
  File "/usr/local/lib/python2.7/dist-packages/dpkt/ip.py", line 309, in <module>

  File "/usr/local/lib/python2.7/dist-packages/dpkt/ip.py", line 305, in __load_protos
    if not hasattr(mod, name.upper()):
AttributeError: 'module' object has no attribute 'AN'
```

**Comment by kbandla** [comment]
@bitonio can please checkout the `fix-imports` branch and see if that solves the problem?

**Comment by bitonio** [comment]
@kbandla fully tested in our code base, it works well thank you!
