### ISSUE TITLE
python dpkt not working suddenly

### ISSUE THREAD

**Issue by sheenawadhwa** [kbandla/dpkt#259]
suddenly my code stoped working i dont know where is the issue
```
Traceback (most recent call last):
  File "D:\Python27\ip print.py", line 10, in <module>
    pcap = dpkt.pcap.Reader(f)
  File "D:\Python27\lib\site-packages\dpkt\pcap.py", line 121, in __init__
    raise ValueError('invalid tcpdump header')
ValueError: invalid tcpdump header
```

code as follow:
```
import dpkt
from dpkt.ip import IP
from dpkt.ethernet import Ethernet
import struct
import socket
import csv

def ip_to_str(address):
    return socket.inet_ntoa(address)

f = open('ipp.pcap', 'rb')
pcap = dpkt.pcap.Reader(f)
print "Ver, HLen, TOS, TLen, ID, Flags, OFF, TTL, Protocol, HChecksum, Source addr, Dest. addr, Payload"

for ts, buf in pcap:
    eth = dpkt.ethernet.Ethernet(buf)
    if eth.type != dpkt.ethernet.ETH_TYPE_IP:
        continue
    ip = eth.data
    do_not_fragment = bool(dpkt.ip.IP_DF)
    more_fragments = bool(dpkt.ip.IP_MF)
    fragment_offset = bool(dpkt.ip.IP_OFFMASK)
    Source = "%s" % ip_to_str(ip.src)
    Destination = "%s" % ip_to_str(ip.dst)
    Length = "%d" % (ip.len)
    TTL = "%d" % (ip.ttl)
    OFF = "%d" % ip.off
    TOS = "%d" % ip.tos
    Protocol = ip.p
    Id = ip.id
    checksum = ip.sum
    ver = ip.v
    hdrlen = dpkt.ip.IP_HDR_LEN
    flags = dpkt.ip.IP_OFFMASK
    payload = "%d" % len(buf)
    print ver, hdrlen, TOS, Length, Id, flags, OFF, TTL, Protocol, checksum, Source, Destination, payload
```

**Comment by kbandla** [comment]
Can you please share the pcap?

**Comment by sheenawadhwa** [comment]
https://drive.google.com/file/d/0BwwWAQYvet7EclVVaFFKODVIX00/view?usp=sharing

**Comment by kbandla** [comment]
Are you passing a python file (`print.py`) to your script, which expects a pcap file?
I just tested your code against the pcap and it works fine.
