### ISSUE TITLE
http.Response packing bug 

### ISSUE THREAD

**Issue by yunzone** [kbandla/dpkt#431]
http.py,241

hhtp.py
def __bytes__(self):
        str_out = '%s/%s %s %s\r\n' % (self.__proto, self.version, self.status,
                                       self.reason) + Message.__str__(self)
        return str_out.encode("ascii", "ignore") + Message.__bytes__(self) 

Message.__str__(self) is appended 2 times

**Comment by obormot** [comment]
Yes definitely looks broken in Python 3. There's no unit test for packing http.Response with body. Needs to be fixed.
```
$ py3
Python 3.7.0 (default, Sep 16 2018, 19:31:10)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
>>> import dpkt
>>> import dpkt.http
>>> resp = dpkt.http.Response()
>>> resp.body = 'foo'
>>> str(resp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../dpkt/http.py", line 239, in __str__
    self.reason) + Message.__str__(self)
  File "/.../dpkt/http.py", line 127, in __str__
    return '%s\r\n%s' % (self.pack_hdr(), self.body.decode("utf8", "ignore"))
AttributeError: 'str' object has no attribute 'decode'
>>>
>>> bytes(resp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../dpkt/http.py", line 243, in __bytes__
    self.reason) + Message.__str__(self)
  File "/.../dpkt/http.py", line 127, in __str__
    return '%s\r\n%s' % (self.pack_hdr(), self.body.decode("utf8", "ignore"))
AttributeError: 'str' object has no attribute 'decode'
>>>
```
