### ISSUE TITLE
Syntax error when I import dpkt

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#44]
_From [snackypants](https://code.google.com/u/snackypants/) on March 26, 2009 14:49:11_

What steps will reproduce the problem? 1. Import dpkt.

Python 2.6.1 ( r261 :67517, Dec  4 2008, 16:51:00) [MSC v.1500 32 bit
(Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
\>>> import dpkt
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "C:\Python26\Lib\site-packages\dpkt\__init__.py", line 17, in \<module>
    import bgp
  File "C:\Python26\lib\site-packages\dpkt\bgp.py", line 678
    self.failUnless(c.as == 65215)
                       ^
SyntaxError: invalid syntax

Once I fixed that, I got this:

\>>> import dpkt
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "C:\Python26\Lib\site-packages\dpkt\__init__.py", line 17, in \<module>
    import bgp
  File "C:\Python26\lib\site-packages\dpkt\bgp.py", line 715
    self.failUnless(b4.open.as == 237)
                             ^

So I fixed that, too. I think the problem is that "as" is a keyword in
Python >= 2.6.

dpkt 1.6 (from Windows EXE installer), on Windows 7 beta, on Python 2.6.1.

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=17_

**Comment by kbandla** [comment]
_From [kosov.p...@gmail.com](https://code.google.com/u/111640130195023752276/) on July 03, 2009 17:21:42_

Same trouble

**Comment by kbandla** [comment]
_From [yard...@gmail.com](https://code.google.com/u/107543518219195225552/) on July 03, 2009 19:57:03_

this was fixed in r51 and r52 of the subversion repository here.  please use that
updated code.

**Status:** Duplicate
