### ISSUE TITLE
BGP: Error reading Extended NLRI routes

### ISSUE THREAD

**Issue by amgadhanafy** [kbandla/dpkt#481]
I tried to read file https://packetlife.net/media/captures/bgp-add-path.cap 

when opened using wireshark it shows the following 

![image](https://user-images.githubusercontent.com/31622061/88215154-85606a00-cc5b-11ea-83fd-08cf1929c154.png)

but when opened using  `dpkt.bgp.BGP(bgp_data)` it gives the following error
```
DEBUG - __main__ - test:308 - ***************cap file : bgp-add-path.cap***************
ERROR - __main__ - extract_features:88 - Error processing BGP data: packet 6 : message 1 of bgp-add-path.cap
ERROR - __main__ - extract_features:89 - BGP_dat(89): b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x59\x02\x00\x00\x00\x30\x40\x01\x01\x00\x40\x02\x06\x02\x01\x00\x00\xfb\xff\x40\x03\x04\x0a\x00\x0e\x01\x80\x04\x04\x00\x00\x00\x00\x40\x05\x04\x00\x00\x00\x64\x80\x0a\x04\x0a\x00\x22\x04\x80\x09\x04\x0a\x00\x0f\x01\x00\x00\x00\x01\x20\x05\x05\x05\x05\x00\x00\x00\x01\x20\xc0\xa8\x01\x05'
ERROR - __main__ - extract_features:90 - invalid ASPathSegment: b'\xfb\xff'
Traceback (most recent call last):
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 95, in __init__
    self.unpack(args[0])
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\bgp.py", line 423, in unpack
    AS = struct.unpack('>H', self.data[:2])[0]
struct.error: unpack requires a buffer of 2 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Amgad\PycharmProjects\bell\bgp_update.py", line 72, in extract_features
    bgp_element = dpkt.bgp.BGP(bgp)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 95, in __init__
    self.unpack(args[0])
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\bgp.py", line 161, in unpack
    self.data = self.update = self.Update(self.data)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 95, in __init__
    self.unpack(args[0])
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\bgp.py", line 272, in unpack
    attr = self.Attribute(self.data)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 95, in __init__
    self.unpack(args[0])
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\bgp.py", line 351, in unpack
    self.data = self.as_path = self.ASPath(self.data)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 95, in __init__
    self.unpack(args[0])
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\bgp.py", line 401, in unpack
    seg = self.ASPathSegment(self.data)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 99, in __init__
    raise UnpackError('invalid %s: %r' %
dpkt.dpkt.UnpackError: invalid ASPathSegment: b'\xfb\xff'
```

**Comment by amgadhanafy** [comment]
@kbandla can you please check this one

**Comment by kbandla** [comment]
Looks like i should run the entire bgp pcap corpus from that collection!

**Comment by amgadhanafy** [comment]
proposed solution

`bgp.py > ASPathSegment`

```
 def unpack(self, buf):
                        dpkt.Packet.unpack(self, buf)
                        l = []
                        for i in range(self.len):
                            # add check on minimum length
                            if len(self.data)> 2:
                                AS = struct.unpack('>H', self.data[:2])[0]
                                self.data = self.data[2:]
                                l.append(AS)
                        self.data = self.path = l
```

**Comment by amgadhanafy** [comment]
@kbandla I think this issue related to Four-Octet Autonomous System (AS) Number Space  https://tools.ietf.org/html/rfc6793

**Comment by amgadhanafy** [comment]
![image](https://user-images.githubusercontent.com/31622061/88965068-82dcc080-d2aa-11ea-866c-f48aeeab70b0.png)

Several issues when processing this packet 
1- unpacked packet length is wrong(90 instead of 89) 
2- announced routes length is wrong (11 instead of 2) routes are resolved as 
`[RouteIPV4(0.0.0.0/0), RouteIPV4(0.0.0.0/0), RouteIPV4(0.0.0.0/0), RouteIPV4(32.0.0.0/1), RouteIPV4(5.0.0.0/5), RouteIPV4(5.0.0.0/5), RouteIPV4(0.0.0.0/0), RouteIPV4(0.0.0.0/0), RouteIPV4(0.0.0.0/0), RouteIPV4(32.0.0.0/1), RouteIPV4(168.1.5.0/192)]`

here is the unit test 
```
    def test_bgp_add_path_6_1_AS_Path(self):
        # Error processing BGP data: packet 6 : message 1 of bgp-add-path.cap https://packetlife.net/media/captures/bgp-add-path.cap
        _bgp = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x59\x02\x00\x00\x00\x30\x40\x01\x01\x00\x40\x02\x06\x02\x01\x00\x00\xfb\xff\x40\x03\x04\x0a\x00\x0e\x01\x80\x04\x04\x00\x00\x00\x00\x40\x05\x04\x00\x00\x00\x64\x80\x0a\x04\x0a\x00\x22\x04\x80\x09\x04\x0a\x00\x0f\x01\x00\x00\x00\x01\x20\x05\x05\x05\x05\x00\x00\x00\x01\x20\xc0\xa8\x01\x05'
        bgp = BGP(_bgp)
        assert (_bgp == bytes((bgp)))
        assert (len(bgp) == 89)
        assert (bgp.type == UPDATE)
        assert (len(bgp.update.withdrawn) == 0)
        assert (len(bgp.update.announced) == 2)

        assert (len(bgp.update.attributes) == 7)

        attribute = bgp.update.attributes[0]
        assert (attribute.type == ORIGIN)
        assert (attribute.optional == False)
        assert (attribute.transitive == True)
        assert (attribute.partial == False)
        assert (attribute.extended_length == False)
        assert (attribute.flags == 0x40)
        assert (attribute.len == 1)
        assert (attribute.origin.type == ORIGIN_IGP)

        attribute = bgp.update.attributes[1]
        assert (attribute.type == AS_PATH)
        assert (attribute.optional == False)
        assert (attribute.transitive == True)
        assert (attribute.partial == False)
        assert (attribute.extended_length == False)
        assert (attribute.flags == 0x40)
        assert (attribute.len == 6)
        assert (len(attribute.as_path.segments) == 1)
        segment = attribute.as_path.segments[0]
        assert (segment.type == AS_SEQUENCE)
        assert (segment.len == 1)
        assert (len(segment.path) == 1)
        assert (segment.path[0] == 64511)

        attribute = bgp.update.attributes[2]
        assert (attribute.type == NEXT_HOP)
        assert (attribute.optional == False)
        assert (attribute.transitive == True)
        assert (attribute.partial == False)
        assert (attribute.extended_length == False)
        assert (attribute.flags == 0x40)
        assert (attribute.len == 4)
        assert (socket.inet_ntop(socket.AF_INET, bytes(attribute.next_hop)) == '10.0.14.1')

        attribute = bgp.update.attributes[3]
        assert (attribute.type == MULTI_EXIT_DISC)
        assert (attribute.optional == True)
        assert (attribute.transitive == False)
        assert (attribute.partial == False)
        assert (attribute.extended_length == False)
        assert (attribute.flags == 0x80)
        assert (attribute.len == 4)
        assert (attribute.multi_exit_disc.value == 0)

        attribute = bgp.update.attributes[4]
        assert (attribute.type == LOCAL_PREF)
        assert (attribute.optional == False)
        assert (attribute.transitive == True)
        assert (attribute.partial == False)
        assert (attribute.extended_length == False)
        assert (attribute.flags == 0x40)
        assert (attribute.len == 4)
        assert (attribute.local_pref.value == 100)

        attribute = bgp.update.attributes[5]
        assert (attribute.type == CLUSTER_LIST)
        assert (attribute.optional == True)
        assert (attribute.transitive == False)
        assert (attribute.partial == False)
        assert (attribute.extended_length == False)
        assert (attribute.flags == 0x80)
        assert (attribute.len == 4)
        assert (socket.inet_ntop(socket.AF_INET, bytes(attribute.cluster_list)) == '10.0.34.4')

        attribute = bgp.update.attributes[6]
        assert (attribute.type == ORIGINATOR_ID)
        assert (attribute.optional == True)
        assert (attribute.transitive == False)
        assert (attribute.partial == False)
        assert (attribute.extended_length == False)
        assert (attribute.flags == 0x80)
        assert (attribute.len == 4)
        assert (socket.inet_ntop(socket.AF_INET, bytes(attribute.originator_id)) == '10.0.15.1')
```

**Comment by amgadhanafy** [comment]
As of [rfc7911](https://tools.ietf.org/html/rfc7911) _Advertisement of Multiple Paths in BGP_
> 3.  Extended NLRI Encodings
> 
>    In order to carry the Path Identifier in an UPDATE message, the NLRI
>    encoding MUST be extended by **prepending the Path Identifier field**,
>    which is of four octets.
> 
>    For example, the NLRI encoding specified in [RFC4271] is extended as
>    the following:
> 
>                   +--------------------------------+
>                   | Path Identifier (4 octets)     |
>                   +--------------------------------+
>                   | Length (1 octet)               |
>                   +--------------------------------+
>                   | Prefix (variable)              |
>                   +--------------------------------+
