### ISSUE TITLE
Error getting multiple paths in BGP update 

### ISSUE THREAD

**Issue by amgadhanafy** [kbandla/dpkt#482]
While trying to open file https://packetlife.net/media/captures/bgplu.cap 
frame 21 
![image](https://user-images.githubusercontent.com/31622061/87363884-73533d00-c572-11ea-8e26-15deb8873f0d.png)

using this code 
```
 bgp_element = dpkt.bgp.BGP(bgp_data)
 update = bgp_element.update
 print(update.attributes)
```
this error is thrown 

```
data:  b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00B\x02\x00\x00\x00+@\x01\x01\x00@\x02\x00@\x03\x04\n\x01\x01\x02@\x05\x04\x00\x00\x00d\x80\x0e\x13\x00\x01\x04\x04\n\x01\x01\x02\x00H\xdb\xc40\xdb\xc4!\x01\x03\x00'
Ethernet Frame:  b'\x00\x00\x00+@\x01\x01\x00@\x02\x00@\x03\x04\n\x01\x01\x02@\x05\x04\x00\x00\x00d\x80\x0e\x13\x00\x01\x04\x04\n\x01\x01\x02\x00H\xdb\xc40\xdb\xc4!\x01\x03\x00'
marker:  ffffffffffffffffffffffffffffffff
type:  2
update:  b'\x00\x00\x00+@\x01\x01\x00@\x02\x00@\x03\x04\n\x01\x01\x02@\x05\x04\x00\x00\x00d\x80\x0e\x13\x00\x01\x04\x04\n\x01\x01\x02\x00H\xdb\xc40\xdb\xc4!\x01\x03\x00'
packed IP wrong length for inet_ntoa


Traceback (most recent call last):
  File "C:/Users/Amgad/PycharmProjects/amgad/bgp.py", line 102, in print_packets
    print(update.attributes)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 138, in __repr__
    ['%s=%r' % (attr_name, attr_value)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 138, in <listcomp>
    ['%s=%r' % (attr_name, attr_value)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 138, in __repr__
    ['%s=%r' % (attr_name, attr_value)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\dpkt.py", line 138, in <listcomp>
    ['%s=%r' % (attr_name, attr_value)
  File "C:\Users\Amgad\PycharmProjects\dpkt\dpkt\bgp.py", line 670, in __repr__
    cidr = '%s/%d' % (socket.inet_ntoa(self.prefix), self.len)
OSError: packed IP wrong length for inet_ntoa
```

**Comment by amgadhanafy** [comment]
As of [rfc3107](https://tools.ietf.org/html/rfc3107) _Advertisement of Multiple Paths in BGP_

> 3. Carrying Label Mapping Information
   Label mapping information is carried as part of the Network Layer    Reachability Information (NLRI) in the Multiprotocol Extensions attributes.  The AFI indicates, as usual, the address family of the associated route.  The fact that the NLRI contains a label is indicated by using SAFI value 4.
The Network Layer Reachability information is encoded as one or more triples of the form <length, label, prefix>, whose fields are described below:
>  ```
>       +---------------------------+
>       |   Length (1 octet)        |
>       +---------------------------+
>       |   Label (3 octets)        |
>       +---------------------------+
>       .............................
>       +---------------------------+
>       |   Prefix (variable)       |
>       +---------------------------+
> ```
>    The use and the meaning of these fields are as follows:
>       a) Length:
>          The Length field indicates the length in bits of the address prefix plus the label(s).
>       b) Label:
>          The Label field carries one or more labels (that corresponds to the stack of labels [MPLS-ENCAPS]).  Each label is encoded as 3 octets, where the high-order 20 bits contain the label value, and the low order bit contains "Bottom of Stack" (as defined in [MPLS-ENCAPS]).
>       c) Prefix:
>          The Prefix field contains address prefixes followed by enough trailing bits to make the end of the field fall on an octet boundary.  Note that the value of trailing bits is irrelevant.

The current implementation is missing this feature
