### ISSUE TITLE
Cannot Install - Python 2.6 - BGP uses 'as' as member name

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#49]
_From [eric.t.a...@gmail.com](https://code.google.com/u/111065915561077602204/) on June 30, 2009 11:16:35_

I get the following when I try to install the library under Python 2.6:

C:\proj\python\dpkt-1.6>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in \<module>
    import dpkt
  File "C:\proj\python\dpkt-1.6\dpkt\__init__.py", line 17, in \<module>
    import bgp
  File "C:\proj\python\dpkt-1.6\dpkt\bgp.py", line 678
    self.failUnless(c.as == 65215)

The problem seems to stem from BGP defining a field that shares the same
name as a keyword: 'as'.  Changing this to 'AS', and changing all
references to the field to the same cleared the issue, and I was able to
install.

The modified file is attached.

**Attachment:** [bgp.py](http://code.google.com/p/dpkt/issues/detail?id=22)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=22_

**Comment by kbandla** [comment]
_From [yard...@gmail.com](https://code.google.com/u/107543518219195225552/) on June 30, 2009 10:39:40_

see r51 and r52 , this has already been corrected in the subversion repository here.

**Status:** Duplicate

**Comment by kbandla** [comment]
_From [acsp...@gmail.com](https://code.google.com/u/103624637359535954585/) on August 22, 2009 10:38:47_

to compile 1.6 (simpler than downloading the file or switching to svn):
cat bgp.py|sed "s/\(['.]\)as\([' ]\)/\1asn\2/" > bgp.py
