### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#52]
_From [enricope...@gmail.com](https://code.google.com/u/117390097584917220270/) on October 01, 2009 11:09:58_

What steps will reproduce the problem? enrico@enrico-laptop:~/workspace/Murena/lib/dpkt-1.6$ sudo python setup.py 
Traceback (most recent call last):
  File "setup.py", line 4, in \<module>
    import dpkt
  File "/home/enrico/workspace/Murena/lib/dpkt-1.6/dpkt/__init__.py", line
17, in \<module>
    import bgp
  File "/home/enrico/workspace/Murena/lib/dpkt-1.6/dpkt/bgp.py", line 678
    self.failUnless(c.as == 65215)
                       ^
SyntaxError: invalid syntax What version of the product are you using? On what operating system? Ubuntu 9.10

Python 2.6.2+ (release26-maint, Sep 24 2009, 06:46:17) 
[GCC 4.4.1] on linux2

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=25_

**Comment by kbandla** [comment]
_From [chad.rhy...@gmail.com](https://code.google.com/u/101800908258414567273/) on October 07, 2009 13:44:57_

I received the same issue.  I am running:

Mac OS X 10.5.8,
Python 2.6.2,
GCC 4.0.1

**Comment by kbandla** [comment]
_From [alrho...@gmail.com](https://code.google.com/u/111948764444239418261/) on October 08, 2009 07:53:09_

I'm runnihg 2.5.2 on Ubuntu, but it could be that "as" is a reserved word in the
member variable "as" .

\>>> class foo:
...     def __init__(self):
...         self.as = 1234
\<stdin>:3: Warning: 'as' will become a reserved keyword in Python 2.6

I would change that member variable to a different name going forward.

**Comment by kbandla** [comment]
_From [chad.rhy...@gmail.com](https://code.google.com/u/101800908258414567273/) on October 09, 2009 09:12:33_

in bgp.py, renaming c.as to c.asn on line 704, and b4.open.as to b4.open.asn on line
741 does make it compile.  When I checked out the code from svn, this problem seems
to be fixed already.  The as member was also corrected to asn in the class
definition, which should fix this bug correctly.

**Comment by kbandla** [comment]
_From [kluik...@gmail.com](https://code.google.com/u/114570438086198244372/) on October 29, 2009 02:06:20_

I'm running 10.6 (python 2.6) and I've gotten past this error, as it's been fixed in the svn branch.

Go checkout the svn trunk and it'll work. I'm now having a different problem though.

**Comment by kbandla** [comment]
_From [phreakmo...@gmail.com](https://code.google.com/u/107536312378532851844/) on March 15, 2010 13:03:49_

Ahh, I fixed it by changing all references to 'as' to 'AS' instead.   I should've
checked here (or the SVN trunk) first.  :-P

**Comment by kbandla** [comment]
_From [dugsong](https://code.google.com/u/dugsong/) on March 25, 2010 19:58:11_

This was fixed 2 years ago in revision 51 . We will cut a new package shortly so we stop 
seeing people running into this.

**Status:** Invalid
