### ISSUE TITLE
dynamic module loading too careless

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#61]
_From [federico...@gmail.com](https://code.google.com/u/109927747085953866358/) on June 20, 2010 10:02:19_

If pigment python is installed, dpkt 1.7 fails with the error below:

Traceback (most recent call last):
  File "./setup.py", line 4, in \<module>
    import dpkt
  File "/usr/obj/i386/py-dpkt-1.7/dpkt-1.7/dpkt/__init__.py", line 24, in \<module>
    import ethernet
  File "/usr/obj/i386/py-dpkt-1.7/dpkt-1.7/dpkt/ethernet.py", line 128, in \<module>
    __load_types()
  File "/usr/obj/i386/py-dpkt-1.7/dpkt-1.7/dpkt/ethernet.py", line 122, in __load_types
    mod = __import__(modname, g)
  File "/usr/obj/i386/py-dpkt-1.7/dpkt-1.7/dpkt/ip6.py", line 95, in \<module>
    import ip
  File "/usr/obj/i386/py-dpkt-1.7/dpkt-1.7/dpkt/ip.py", line 255, in \<module>
    __load_protos()
  File "/usr/obj/i386/py-dpkt-1.7/dpkt-1.7/dpkt/ip.py", line 252, in __load_protos
    IP.set_proto(v, getattr(mod, name.upper()))
AttributeError: 'module' object has no attribute 'PGM'

This was found in OpenBSD 4.7/x86 but the error is not OS specific.
Attached diff should fix it.
Thanks.

**Attachment:** [dpkt.diff](http://code.google.com/p/dpkt/issues/detail?id=34)

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=34_

**Comment by kbandla** [comment]
_From [e.najda...@gmail.com](https://code.google.com/u/103405961500002997098/) on May 12, 2012 07:55:55_

Suggested solution is not good, because it will just mask the problem.  Better to add level=1 parameter to all imports (see diff).

**Attachment:** [dpkt-imports.diff](http://code.google.com/p/dpkt/issues/detail?id=34#hc2)

**Comment by kbandla** [comment]
_From [ki...@kiddaland.net](https://code.google.com/u/111743600165148955252/) on December 16, 2013 13:22:23_

changing the line to 
                mod = __import__('dpkt.{}'.format(name), g)
should also fix it...

**Comment by kbandla** [comment]
Fixed in d7684fe195c09552a6c005c89a0055f516e16588. Tracked in #203
