### ISSUE TITLE
No PPI Support

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#72]
_From [pedrogfr...@gmail.com](https://code.google.com/u/105103961488205321035/) on August 17, 2010 13:00:57_

What steps will reproduce the problem? 1. Get a PCAP with PPI info (e.g., in Kismet)
2. Try to open it using dpkt with the code on http://www.jjguy.com/pcaputils/ What is the expected output? What do you see instead? I see:
Traceback (most recent call last):
  File "parser2.py", line 4, in \<module>
    pcapReader = dpkt.pcap.Reader(file(sys.argv[1], "rb"))
  File "/usr/lib/pymodules/python2.6/dpkt/pcap.py", line 105, in __init__
    self.dloff = dltoff[self.__fh.linktype]
KeyError: 192 What version of the product are you using? On what operating system? 1.6+svn54-1 on Ubuntu 10.04 Please provide any additional information below. http://nmap.org/svn/libpcap/pcap-common.c defines 'LINKTYPE_PPI' as '192'. http://www.cacetech.com/documents/PPI&#37;20Header&#37;20format&#37;201.0.9.pdf provides PPI spec.

NOTE: even if it isn't worth it to support PPI may I sugest a better error message for it than an exception?

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=45_

**Comment by kbandla** [comment]
_From [pedrogfr...@gmail.com](https://code.google.com/u/105103961488205321035/) on August 23, 2010 08:56:07_

Also as a nicer way to fail, it can suggest using tool 'wlan2eth' described on http://www.securityfocus.com/archive/137/506588/30/60/threaded to strip the PPI headers (the wlan2eth's actual homepage is http://www.willhackforsushi.com/?page_id=79 ) before exiting with an error.
